const CANVAS_DESIGN_GUIDANCE_LINES = [
  "## Quality standard: Design for Humans, Not Algorithms",
  "",
  "A technically valid render is not necessarily a good result. The artifact must be clear, deliberate, visually coherent, and designed for real human use—not a technical document or a checklist-driven prototype.",
  "",
  "- **Put the user first:** The user's brief, supplied content, references, and existing visual system take absolute priority over generic taste rules.",
  "- **Form follows function:** Every design decision should support the artifact's purpose, content, audience, or viewing context. Make the primary object or action visible immediately. Check that a new user can start the main task within five seconds.",
  "- **Layout is meaning:** Reading order, grouping, alignment, scale, and spacing must make the content easier to understand.",
  "- **Aggressive restraint:** Restraint is the default. Cut decorative clutter aggressively. Add an element only when it improves comprehension, navigation, emphasis, atmosphere, or interaction.",
  "- **Pixels matter:** Inspect the rendered result itself. Good intentions in the source code do not compensate for weak, sloppy, or generic pixels.",
  "",
  "## Before building",
  "",
  "Establish the following before choosing colors or writing layout code:",
  "",
  "1. **Purpose:** What should this artifact help someone understand, decide, remember, or do?",
  "2. **Audience:** Who will see it, what do they already know, and under what conditions will they view it?",
  "3. **Content:** What information is required, what is supporting detail, and what must be removed?",
  "4. **Format:** Is this primarily something to present, read, scan, print, explore, or operate?",
  "5. **Visual context:** Does the user provide a brand, reference, existing artifact, or established visual language that should be preserved?",
  "",
  "If the brief leaves the visual direction open, derive it from the specific subject rather than falling back on a fashionable, generic template. Identify a compact design system before implementation:",
  "",
  "- A one-sentence visual thesis.",
  "- The content hierarchy and explicit reading path.",
  "- A palette with defined structural roles.",
  "- Typography roles and a clear scale.",
  "- The grid, margins, and a strict spacing rhythm.",
  "- One distinctive visual idea, when the subject benefits from one.",
  "",
  "The distinctive idea should make the work specific, not make it louder. Spend visual boldness where it matters and keep the surrounding system disciplined.",
  "",
  "## Design principles",
  "",
  "### Structure must make sense",
  "",
  "- Organize around the real information or task, not around a collection of floating components. Avoid generic forms when direct manipulation makes more sense.",
  "- Make the primary message, object, or action obvious within seconds.",
  "- Use position, scale, contrast, and whitespace to establish hierarchy *before* adding borders, shadows, labels, or decoration.",
  "- Use a grid. Elements that appear aligned should share exact edges, centers, baselines, or gutters.",
  "- Group related content tightly and separate unrelated content clearly.",
  "- Keep repeated spacing intentional. Similar relationships should use similar gaps.",
  "- Preserve a clear reading order. Do not make the viewer zigzag through arbitrary, randomized placements.",
  "- Use asymmetry only when it improves emphasis, movement, or balance. Random misalignment is not expressive design.",
  "- Leave enough space around important content. Empty space is useful when it clarifies structure; it is wasteful when it merely leaves the page unfinished.",
  "- Do not force every page or section into the same predictable composition. Repetition should create rhythm, not expose a template.",
  "",
  "### Typography must carry hierarchy",
  "",
  "- Choose typefaces that fit the subject and remain legible in the delivery format.",
  "- Define explicit roles for display text, headings, body text, captions, labels, and data.",
  "- Prefer one type family with sufficient range, or a deliberate pairing. Do not add typefaces simply to make the artifact feel \"designed.\"",
  "- Use a clear type scale with visibly distinct levels. Avoid a page where every line has nearly the same size and weight.",
  "- Keep one clear heading and one short supporting line where applicable.",
  "- Set line height, measure, tracking, and paragraph spacing deliberately.",
  "- Keep body text comfortably readable. Do not shrink text to rescue an overcrowded layout; edit the content or change the composition.",
  "- Control line breaks in prominent text. Avoid accidental single-word lines, awkward wraps, widows, and orphans.",
  "- Use emphasis sparingly. When everything is bold, colored, boxed, or oversized, nothing is emphasized.",
  "- Treat numbers, charts, and labels as typography, not as raw browser output.",
  "",
  "### Copy must be useful and natural (Anti-Slop)",
  "",
  "Words in a visual artifact exist to help the viewer understand or act. They are not decorative filler. Design for actual repeated use, not just a screenshot.",
  "",
  "- **Use plain, concrete, human copy.** Use the user's real copy and data when provided. Do not replace factual content with invented claims.",
  "- Keep headings meaningful and supporting copy concise.",
  "- Let each text element do one job. A heading identifies; a label labels; a caption adds necessary context; a control names its action.",
  "- **Eradicate filler:** Remove copy that repeats the heading, narrates the interface, announces the design concept, or fills an empty region.",
  "- **No fake marketing:** Do not invent slogans, slogan stacks, inspirational fragments, pseudo-insightful statements, fake quotations, fake metrics, fake testimonials, or vague product claims.",
  "- **Ban inflated language:** Avoid words like “reimagining,” “unlocking,” “seamless,” “intelligent,” “robust,” or “next generation” unless it is supplied copy or conveys a precise, testable fact.",
  "- **Cut UI theater:** Do not add eyebrow text, category pills, tiny uppercase pre-headings, or ornamental labels merely to make a composition look \"complete.\"",
  "- Use consistent terminology. The same action or concept should keep the same name throughout.",
  "- For controls, say what will happen. For errors, say what went wrong and how to recover.",
  "- If removing text improves clarity without losing meaning, delete it.",
  "",
  "### Color must be intentional",
  "",
  "- Derive the palette from the subject, brand, content, and viewing environment.",
  "- Assign roles to colors: background, surface, primary text, secondary text, accent, border, and semantic states.",
  "- Use a restrained visual hierarchy and color system. Let the main workspace receive most of the visual attention.",
  "- Maintain readable contrast, including for small text and text placed over images.",
  "- Prefer tinted secondary colors that belong to the palette over arbitrary default gray when working on colored surfaces.",
  "- **Ban AI defaults:** Do not automatically use purple-blue gradients, cyan glows, neon accents on dark backgrounds, warm cream with terracotta, or any other recognizable AI-default palette designed to mask a lack of substantive content.",
  "- Do not automatically soften white into cream or black into blue-gray. Choose the actual background the design functionally needs.",
  "- Gradients are allowed *only* when they have a specific compositional or atmospheric role. They are not a substitute for art direction.",
  "- Avoid gradient text entirely unless the brief specifically calls for it and readability remains excellent.",
  "",
  "### Containers and decoration must earn their place",
  "",
  "- A card should communicate a real grouping, boundary, state, or interaction. It should not be the default container for every piece of content.",
  "- **Avoid UI clichés:** Avoid nested cards, repeated rounded rectangles, excessive bubbles, feature pills, and boxed sections that could simply be expressed with alignment and spacing.",
  "- Do not turn a page into a uniform grid of icon, heading, and paragraph cards unless the content truly is a set of equivalent, independent items.",
  "- Use border radius consistently and with intent. Not every object needs rounded corners.",
  "- Use borders to clarify structure, not to outline every region.",
  "- Shadows should explain depth or separation. Avoid ambient colored halos and soft glows used only to make a surface look “AI.”",
  "- Use glass and blur only when translucency has a functional or material reason.",
  "- Do not add ornamental icons, badges, sparklines, progress rings, or miniature charts to stand in for missing content.",
  "- Use a coherent icon system with consistent geometry, stroke, weight, optical size, and alignment. Do not use emoji or random Unicode glyphs as interface icons.",
  "- Use monospace for code, identifiers, measurements, or data—not as a costume for technical subject matter.",
  "- Section numbers such as `01 / 02 / 03` are appropriate only when sequence or reference matters.",
  "",
  "### Images, diagrams, and data graphics must do real work",
  "",
  "- Use imagery when it conveys subject matter, evidence, atmosphere, or narrative more effectively than text.",
  "- Choose crops and aspect ratios deliberately. Protect faces, labels, focal objects, and safe areas for overlaid text.",
  "- Do not use a decorative image that competes with the information or creates a false focal point.",
  "- Charts should answer a specific question. Choose the simplest form that makes the comparison or trend clear.",
  "- Label data directly when practical, minimize chart furniture, and make the important series unmistakable.",
  "- Diagrams should express actual relationships. Do not add arbitrary arrows, nodes, or flow lines for the sake of visual complexity.",
  "- Keep visual style consistent across illustrations, photographs, charts, icons, and diagrams.",
  "",
  "### Motion and interaction must have a purpose",
  "",
  "- Use motion to explain state, sequence, causality, focus, or spatial change.",
  "- Prefer one or two authored moments over many unrelated entrance effects.",
  "- Do not animate every element merely because the artifact is rendered in a browser.",
  "- Use the interaction people naturally expect for this kind of product.",
  "- Keep controls functional and states visible. Interactive artifacts should support keyboard focus and understandable hover, active, disabled, loading, empty, and error states where relevant.",
  "- Respect `prefers-reduced-motion`.",
  "- The core interaction should be obvious without explanatory marketing copy or a decorative landing page wrapped around it.",
  "",
  "## Format-specific guidance",
  "",
  "### Slide decks",
  "",
  "- Give each slide one primary job and a clear focal point.",
  "- Build a narrative across the deck: establish context, develop the argument, show evidence, and land the conclusion.",
  "- Keep text presentable at normal presentation distance. Move detail into notes or supporting pages rather than shrinking it.",
  "- Vary composition according to the content while preserving a coherent system of type, color, margins, and recurring elements.",
  "- Do not repeat the same generic title-plus-card-grid layout on every slide.",
  "- Use charts, diagrams, quotations, and imagery when they communicate better than bullet lists.",
  "- Treat the cover and section dividers as part of the same design system, not as unrelated posters.",
  "",
  "### Reports and handouts",
  "",
  "- Optimize for sustained reading, scanning, and reference.",
  "- Use a stable page grid, clear heading hierarchy, sensible paragraph measure, and predictable navigation.",
  "- Keep tables readable and repeat headers when appropriate.",
  "- Place figures near the text that explains them and write captions that add context rather than restate titles.",
  "- Control page breaks so headings, captions, rows, and related content are not stranded.",
  "- Use decoration sparingly; editorial clarity outranks spectacle.",
  "",
  "### Posters and one-pagers",
  "",
  "- Establish one dominant focal point and one clear reading path.",
  "- Keep only the text the viewer can realistically absorb in the viewing context.",
  "- Use scale, image, typography, and negative space as the main compositional tools.",
  "- Ensure practical details remain findable and legible after the initial visual impact.",
  "",
  "### Dashboards and interactive artifacts",
  "",
  "- Put the real working surface first. Do not add a marketing hero above an operational interface unless the user explicitly requests one.",
  "- Organize around the primary task, important state, and decisions the viewer must make.",
  "- Use cards *only* where each card represents a meaningful object or independent unit.",
  "- Make filters, selections, legends, controls, and status changes unambiguous.",
  "- Use realistic states and content. A polished, empty shell with fake metrics is not a finished dashboard."
] as const;

export function buildCanvasDesignGuidance(): string {
  return `${CANVAS_DESIGN_GUIDANCE_LINES.join("\n")}\n`;
}
