import type {
  Response,
  ResponseFunctionToolCall,
  ResponseInputItem,
  Tool
} from "openai/resources/responses/responses";
import type { PlatformModelCompatibilityMode, PlatformModelType, PlatformUsageBilling, TaskSource } from "@meowbert/shared";
import { streamResponseToFinal } from "@meowbert/shared";
import { getAbortError, throwIfAborted } from "../../lib/abort-signal.js";
import { config } from "../../lib/config.js";
import { query } from "../../lib/db.js";
import { emitTaskEvent } from "../runtime/events.js";
import { getOpenAiClient, type OpenAiProviderConfig } from "./openai-client.js";
import { platformUsageRecorder } from "../tasks/platform-usage.js";
import { emitNetworkRequestEvent, type NetworkRequestLogEvent, type NetworkRequestLogCallback } from "./network-request-log.js";
import { withOpenAiRequestDebugLogging } from "./openai-sdk-logger.js";
import { extractNetworkRequestErrorResponse } from "./model-error-response-log.js";
import {
  TASK_TITLE_FUNCTION_TOOL,
  TASK_TITLE_SYSTEM_PROMPT,
  TASK_TITLE_TOOL_NAME,
  taskTitleArgumentsSchema
} from "../agent-tools/index.js";
import type { TaskMessageRow } from "./types.js";
import {
  applySourceTitlePrefix,
  asText,
  isAutoGeneratedTitlePlaceholder,
  isFunctionCallItem,
  normalizeTitleCandidate,
  parseToolArguments
} from "./utils.js";
import { parseMissingToolOutputCallId, resolveModelErrorAction } from "./model-error-actions.js";
import { normalizeProviderRequestInput } from "./provider-request-input.js";
import { normalizeProviderRequestTools } from "./provider-request-tools.js";
import { buildTaskDecisionContext } from "./task-decision-context.js";
import {
  buildChatGptCodexInstructions,
  buildChatGptCodexProvider,
  isChatGptCodexProvider
} from "./chatgpt-request.js";
import type { MemoryMainFile } from "../memory/index.js";
import type { WorkspaceImageDetail } from "../workspaces/workspace-model-settings.js";

function stableSortObjectKeys(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => stableSortObjectKeys(entry));
  }

  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort((a, b) => a.localeCompare(b));
    const sorted: Record<string, unknown> = {};
    for (const key of keys) {
      sorted[key] = stableSortObjectKeys(record[key]);
    }
    return sorted;
  }

  return value;
}

function canonicalizeModelPayload(modelPayload: Record<string, unknown>): Record<string, unknown> {
  return stableSortObjectKeys(modelPayload) as Record<string, unknown>;
}

function attachResponseStreamEvents(target: object, events: unknown[]): void {
  Object.defineProperty(target, "__meowbertResponseStreamEvents", {
    value: events,
    enumerable: false,
    configurable: true
  });
}

function readResponseStreamEvents(target: unknown): unknown[] {
  return target instanceof Error || (typeof target === "object" && target !== null)
    ? ((target as { __meowbertResponseStreamEvents?: unknown[] }).__meowbertResponseStreamEvents ?? [])
    : [];
}

function toolSortKey(tool: Tool): string {
  const toolRecord = tool as unknown as Record<string, unknown>;
  const type = typeof toolRecord.type === "string" ? toolRecord.type : "unknown";
  const name = typeof toolRecord.name === "string" ? toolRecord.name : "";
  return `${type}:${name}`;
}

export function normalizeToolsForRequest(tools: Tool[]): Tool[] {
  return [...tools].sort((left, right) => {
    return toolSortKey(left).localeCompare(toolSortKey(right));
  });
}

export type ModelNetworkRequestEvent = NetworkRequestLogEvent;

export type ModelToolChoice = "required" | "auto" | {
  type: "function";
  name: string;
};

type CreateModelResponseInput = {
  provider: OpenAiProviderConfig;
  model: string;
  modelType?: PlatformModelType;
  compatibilityModes?: PlatformModelCompatibilityMode[];
  requestTimeoutMs?: number;
  abortSignal?: AbortSignal;
  cacheUserId?: string;
  promptCacheKey?: string;
  promptCacheTtl?: "30m";
  cacheKeepaliveSeconds?: number;
  prefixItems: ResponseInputItem[];
  conversationItems: ResponseInputItem[];
  modelPayload: Record<string, unknown>;
  maxOutputTokens?: number;
  tools: Tool[];
  toolChoice?: ModelToolChoice;
  parallelToolCalls?: boolean;
  onNetworkRequest?: NetworkRequestLogCallback;
  requestEndpoint?: string;
  requestAttempt?: number;
  requestSessionId?: string;
};

function trimTrailingSlashes(value: string): string {
  return value.replace(/\/+$/, "");
}

function resolveResponsesRequestUrl(baseUrl: string): string {
  return `${trimTrailingSlashes(baseUrl)}/responses`;
}

function shellEscapeSingleQuoted(value: string): string {
  return value.replace(/'/g, `'\"'\"'`);
}

function buildReplayHeaders(
  provider: OpenAiProviderConfig,
  requestHeaders: Record<string, string>
): Record<string, string> {
  return {
    "content-type": "application/json",
    accept: "text/event-stream",
    authorization: provider.apiKey.trim().length > 0 ? "Bearer <REPLACE_WITH_API_KEY>" : "Bearer <ADD_API_KEY>",
    ...(provider.defaultHeaders ?? {}),
    ...requestHeaders
  };
}

// Proxies that resume upstream sessions (e.g. Meridian) key conversations on this header;
// without it every tool round replays as a fresh session and loses the prompt cache.
// Meridian also keeps that session's prompt cache warm for the requested window.
function buildModelRequestHeaders(
  input: Pick<CreateModelResponseInput, "promptCacheKey" | "cacheKeepaliveSeconds">
): Record<string, string> {
  if (typeof input.promptCacheKey !== "string" || input.promptCacheKey.length === 0) {
    return {};
  }
  return {
    "x-session-affinity": input.promptCacheKey,
    ...(input.cacheKeepaliveSeconds ? { "x-meridian-cache-keepalive": String(input.cacheKeepaliveSeconds) } : {})
  };
}

function buildCurlCommand(input: {
  method: string;
  url: string;
  headers: Record<string, string>;
  body: Record<string, unknown>;
}): string {
  const lines = [
    `curl \\\n  '${shellEscapeSingleQuoted(input.url)}' \\`
  ];
  lines.splice(1, 0, `  -X ${input.method} \\`);

  for (const [key, value] of Object.entries(input.headers)) {
    lines.push(`  -H '${shellEscapeSingleQuoted(`${key}: ${value}`)}' \\`);
  }

  lines.push(`  --data-binary '${shellEscapeSingleQuoted(JSON.stringify(input.body, null, 2))}'`);
  return lines.join("\n");
}

function buildReplayPayload(input: {
  provider: OpenAiProviderConfig;
  requestBody: Record<string, unknown>;
  requestHeaders?: Record<string, string>;
}) {
  const method = "POST";
  const url = resolveResponsesRequestUrl(input.provider.baseUrl);
  const headers = buildReplayHeaders(input.provider, input.requestHeaders ?? {});
  const body = {
    ...input.requestBody,
    stream: true
  };

  return {
    method,
    url,
    headers,
    body,
    curl: buildCurlCommand({
      method,
      url,
      headers,
      body
    })
  };
}

function buildModelRequestPayload(input: CreateModelResponseInput): Record<string, unknown> {
  const chatGptCodex = isChatGptCodexProvider(input.provider);
  const modelType = input.modelType ?? "openai";
  const requestInput = normalizeProviderRequestInput(
    [...(chatGptCodex ? [] : input.prefixItems), ...input.conversationItems],
    modelType,
    input.compatibilityModes ?? []
  );
  const normalizedModelPayload = canonicalizeModelPayload(input.modelPayload);
  const normalizedTools = normalizeToolsForRequest(normalizeProviderRequestTools(input.tools, modelType));
  const promptCacheOptions: Record<string, unknown> = {};

  if (typeof input.promptCacheKey === "string" && input.promptCacheKey.length > 0) {
    promptCacheOptions.prompt_cache_key = input.promptCacheKey;
  }
  if (!chatGptCodex && input.promptCacheTtl === "30m") {
    promptCacheOptions.prompt_cache_options = {
      ttl: input.promptCacheTtl
    };
  }

  const requestPayload: Record<string, unknown> = {
    ...normalizedModelPayload,
    ...(input.maxOutputTokens ? { max_output_tokens: input.maxOutputTokens } : {}),
    ...promptCacheOptions,
    model: input.model,
    input: requestInput,
    include: ["reasoning.encrypted_content"],
    store: false,
    tools: normalizedTools,
    tool_choice: input.toolChoice ?? "required",
    parallel_tool_calls: input.parallelToolCalls ?? (normalizedModelPayload.parallel_tool_calls as boolean | undefined) ?? true,
    ...(!chatGptCodex && typeof input.cacheUserId === "string" && input.cacheUserId.length > 0
      ? { user: input.cacheUserId }
      : {})
  };

  if (chatGptCodex) {
    const instructions = buildChatGptCodexInstructions(input.prefixItems);
    if (instructions.length > 0) {
      requestPayload.instructions = instructions;
    }
  }

  return requestPayload;
}

export async function createModelResponse(input: CreateModelResponseInput): Promise<Response> {
  const requestTimeoutMs = resolveRequestTimeoutMs(input.requestTimeoutMs);
  const requestProvider = buildChatGptCodexProvider(input.provider, input.requestSessionId);
  const client = createResponsesClient({
    provider: requestProvider,
    model: input.model,
    onNetworkRequest: input.onNetworkRequest,
    endpoint: input.requestEndpoint ?? "responses.create",
    attempt: input.requestAttempt ?? 1
  });
  const requestPayload = buildModelRequestPayload(input);
  const requestHeaders = buildModelRequestHeaders(input);
  const responseStreamEvents: unknown[] | undefined = input.onNetworkRequest ? [] : undefined;

  const response: Response = await streamResponseToFinal(client, requestPayload, {
    maxRetries: 0,
    timeout: requestTimeoutMs,
    ...(Object.keys(requestHeaders).length > 0 ? { headers: requestHeaders } : {}),
    ...(input.abortSignal ? { signal: input.abortSignal } : {})
  }, {
    onEvent: (event) => {
      responseStreamEvents?.push(event);
    }
  }).catch((error: unknown) => {
    if (responseStreamEvents && error instanceof Error) {
      attachResponseStreamEvents(error, responseStreamEvents);
    }
    throw error;
  });

  if (responseStreamEvents) {
    attachResponseStreamEvents(response as object, responseStreamEvents);
  }
  if (response.error) {
    throw Object.assign(new Error(response.error.message), {
      error: response.error
    });
  }

  for (const item of response.output) {
    if (item.type === "function_call" && (typeof item.call_id !== "string" || item.call_id.length === 0)) {
      throw new Error("Model response contained a function call without a call_id.");
    }
  }

  return response;
}

const MODEL_REQUEST_MAX_RETRIES = 5;
const MODEL_REQUEST_BASE_DELAY_MS = 15_000;
const MODEL_REQUEST_RECOVERY_ERROR_THRESHOLD = 3;
const DEFAULT_MODEL_REQUEST_TIMEOUT_MS = 5 * 60 * 1000;

function resolveRequestTimeoutMs(requestTimeoutMs: number | undefined): number {
  if (typeof requestTimeoutMs !== "number" || !Number.isFinite(requestTimeoutMs)) {
    return DEFAULT_MODEL_REQUEST_TIMEOUT_MS;
  }

  const floored = Math.floor(requestTimeoutMs);
  return floored > 0 ? floored : DEFAULT_MODEL_REQUEST_TIMEOUT_MS;
}

function createResponsesClient(input: {
  provider: OpenAiProviderConfig;
  model: string;
  endpoint: string;
  attempt: number;
  onNetworkRequest?: NetworkRequestLogCallback;
}) {
  const client = getOpenAiClient(input.provider);
  if (!input.onNetworkRequest) {
    return client;
  }

  return withOpenAiRequestDebugLogging(client, {
    endpoint: input.endpoint,
    model: input.model,
    baseUrl: input.provider.baseUrl,
    attempt: input.attempt,
    onNetworkRequest: input.onNetworkRequest
  });
}

async function sleepWithOptionalAbort(ms: number, signal: AbortSignal | undefined): Promise<void> {
  throwIfAborted(signal);

  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      if (signal) {
        signal.removeEventListener("abort", onAbort);
      }
      resolve();
    }, ms);

    function onAbort(): void {
      clearTimeout(timeout);
      reject(getAbortError(signal) ?? new Error("TASK_CANCELLED"));
    }

    if (signal) {
      signal.addEventListener("abort", onAbort, { once: true });
    }
  });
}

export async function createModelResponseWithRetry(
  taskId: string,
  input: CreateModelResponseInput & {
    onConsecutiveErrorRecovery?: (errorMessage: string) => Promise<boolean>;
  },
  onRetryMessage?: (message: string) => Promise<void>
): Promise<Response> {
  let lastError: Error | null = null;
  let consecutiveErrorCount = 0;
  let attempt = 0;
  const requestSessionId = input.requestSessionId ?? taskId;
  const requestInput = { ...input, requestSessionId };
  throwIfAborted(input.abortSignal);

  while (attempt <= MODEL_REQUEST_MAX_RETRIES) {
    throwIfAborted(input.abortSignal);
    const attemptNo = attempt + 1;
    const requestStartedAt = Date.now();
    await emitNetworkRequestEvent(input.onNetworkRequest, {
      phase: "start",
      service: "openai_responses",
      endpoint: "responses.create",
      model: input.model,
      baseUrl: input.provider.baseUrl,
      attempt: attemptNo,
      request: buildReplayPayload({
        provider: buildChatGptCodexProvider(input.provider, requestSessionId),
        requestBody: buildModelRequestPayload(requestInput),
        requestHeaders: buildModelRequestHeaders(requestInput)
      })
    });
    try {
      const response = await createModelResponse({
        ...requestInput,
        requestEndpoint: "responses.create",
        requestAttempt: attemptNo
      });
      await emitNetworkRequestEvent(input.onNetworkRequest, {
        phase: "success",
        service: "openai_responses",
        endpoint: "responses.create",
        model: input.model,
        baseUrl: input.provider.baseUrl,
        attempt: attemptNo,
        durationMs: Date.now() - requestStartedAt,
        responseStream: {
          events: readResponseStreamEvents(response)
        }
      });
      return response;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const errorResponse = extractNetworkRequestErrorResponse(err);
      await emitNetworkRequestEvent(input.onNetworkRequest, {
        phase: "error",
        service: "openai_responses",
        endpoint: "responses.create",
        model: input.model,
        baseUrl: input.provider.baseUrl,
        attempt: attemptNo,
        durationMs: Date.now() - requestStartedAt,
        error: message,
        ...(errorResponse ? { errorResponse } : {}),
        responseStream: {
          events: readResponseStreamEvents(err)
        }
      });
      if (
        err instanceof Error
        && (err.message === "TASK_CANCELLED" || err.message === "RUN_TIME_LIMIT_REACHED")
      ) {
        throw err;
      }

      const abortError = getAbortError(input.abortSignal);
      if (abortError) {
        throw abortError;
      }

      lastError = err instanceof Error ? err : new Error(String(err));
      consecutiveErrorCount += 1;

      if (resolveModelErrorAction(lastError) !== null) {
        throw lastError;
      }

      const isMissingToolOutput = parseMissingToolOutputCallId(lastError.message) !== null;
      if (
        (consecutiveErrorCount >= MODEL_REQUEST_RECOVERY_ERROR_THRESHOLD || isMissingToolOutput)
        && input.onConsecutiveErrorRecovery
        && await input.onConsecutiveErrorRecovery(lastError.message)
      ) {
        consecutiveErrorCount = 0;
        attempt = 0;
        continue;
      }

      if (attempt === MODEL_REQUEST_MAX_RETRIES) {
        break;
      }

      const delayMs = MODEL_REQUEST_BASE_DELAY_MS * Math.pow(2, attempt);
      const retryMsg = `Model request failed (attempt ${attempt + 1}/${MODEL_REQUEST_MAX_RETRIES + 1}): ${lastError.message}. Retrying in ${(delayMs / 1000).toFixed(0)}s...`;

      if (onRetryMessage) {
        await onRetryMessage(retryMsg);
      }
      await emitTaskEvent(taskId, "error", {
        message: retryMsg,
        attempt: attempt + 1,
        maxAttempts: MODEL_REQUEST_MAX_RETRIES + 1,
        retrying: true
      });

      await sleepWithOptionalAbort(delayMs, input.abortSignal);
      attempt += 1;
    }
  }

  throw lastError!;
}

export async function maybeAutoGenerateTaskTitle(input: {
  provider: OpenAiProviderConfig;
  billing: PlatformUsageBilling | null;
  taskId: string;
  currentTitle: string | null;
  source: TaskSource;
  messages: TaskMessageRow[];
  taskInputDir?: string | null;
  memoryMainFile?: MemoryMainFile | null;
  projectMemoryMainFile?: MemoryMainFile | null;
  imageDetail?: WorkspaceImageDetail;
  model?: string;
  compatibilityModes?: PlatformModelCompatibilityMode[];
  requestTimeoutMs?: number;
  abortSignal?: AbortSignal;
  onNetworkRequest?: NetworkRequestLogCallback;
}): Promise<void> {
  if (input.abortSignal?.aborted) {
    return;
  }

  const existingTitle = input.currentTitle?.trim() ?? "";
  if (existingTitle.length > 0 && !isAutoGeneratedTitlePlaceholder(existingTitle)) {
    return;
  }

  const firstUserMessage = input.messages.find((message) => message.role === "user");
  if (!firstUserMessage) {
    return;
  }

  const firstMessageText = asText(firstUserMessage.content_json).trim();
  const firstMessageHasAttachments =
    Array.isArray(firstUserMessage.content_json.attachments)
    && firstUserMessage.content_json.attachments.length > 0;
  if (firstMessageText.length === 0 && !firstMessageHasAttachments) {
    return;
  }

  try {
    const requestTimeoutMs = resolveRequestTimeoutMs(input.requestTimeoutMs);
    const titleModel = input.model ?? config.openai.defaultModel;
    const decisionContext = await buildTaskDecisionContext({
      messages: input.messages,
      taskInputDir: input.taskInputDir,
      memoryMainFile: input.memoryMainFile,
      projectMemoryMainFile: input.projectMemoryMainFile,
      imageDetail: input.imageDetail,
      mode: "first_user"
    });
    const client = createResponsesClient({
      provider: buildChatGptCodexProvider(input.provider, input.taskId),
      model: titleModel,
      endpoint: "responses.create.title",
      attempt: 1,
      onNetworkRequest: input.onNetworkRequest
    });
    const titlePromptItems: ResponseInputItem[] = [
      {
        role: "system",
        content: TASK_TITLE_SYSTEM_PROMPT
      },
      {
        role: "user",
        content: [
          "Summarize the task using the bounded context below.",
          "Use the user's request as the primary signal; use attachment and memory context only to make the title more specific.",
          "",
          decisionContext.text,
          "",
          "Remember: output only the task title text."
        ].join("\n")
      },
      ...decisionContext.imageItems
    ];
    const titleRequestItems = isChatGptCodexProvider(input.provider)
      ? titlePromptItems.slice(1)
      : titlePromptItems;
    const requestInput = normalizeProviderRequestInput(titleRequestItems, "openai", input.compatibilityModes ?? []);
    const requestBody = {
      model: titleModel,
      ...(isChatGptCodexProvider(input.provider) ? { instructions: TASK_TITLE_SYSTEM_PROMPT } : {}),
      input: requestInput,
      tools: [TASK_TITLE_FUNCTION_TOOL],
      tool_choice: {
        type: "function",
        name: TASK_TITLE_TOOL_NAME
      },
      parallel_tool_calls: false,
      max_output_tokens: 32,
      store: false
    } as const;
    const requestStartedAt = Date.now();
    const responseStreamEvents: unknown[] | undefined = input.onNetworkRequest ? [] : undefined;
    await emitNetworkRequestEvent(input.onNetworkRequest, {
      phase: "start",
      service: "openai_responses",
      endpoint: "responses.create.title",
      model: titleModel,
      baseUrl: input.provider.baseUrl,
      attempt: 1,
      request: buildReplayPayload({
        provider: input.provider,
        requestBody
      })
    });
    const titleResponse: Response = await streamResponseToFinal(client, requestBody, {
      maxRetries: 0,
      timeout: requestTimeoutMs,
      ...(input.abortSignal ? { signal: input.abortSignal } : {})
    }, {
      onEvent: (event) => {
        responseStreamEvents?.push(event);
      }
    }).catch((error: unknown) => {
      if (responseStreamEvents && error instanceof Error) {
        attachResponseStreamEvents(error, responseStreamEvents);
      }
      throw error;
    });
    await platformUsageRecorder.recordResponseUsage(input.billing, titleModel, titleResponse.usage);
    if (titleResponse.error) {
      await emitNetworkRequestEvent(input.onNetworkRequest, {
        phase: "error",
        service: "openai_responses",
        endpoint: "responses.create.title",
        model: titleModel,
        baseUrl: input.provider.baseUrl,
        attempt: 1,
        durationMs: Date.now() - requestStartedAt,
        error: titleResponse.error.message,
        errorResponse: {
          body: {
            error: titleResponse.error
          }
        },
        responseStream: {
          events: responseStreamEvents ?? []
        }
      });
      return;
    }

    await emitNetworkRequestEvent(input.onNetworkRequest, {
      phase: "success",
      service: "openai_responses",
      endpoint: "responses.create.title",
      model: titleModel,
      baseUrl: input.provider.baseUrl,
      attempt: 1,
      durationMs: Date.now() - requestStartedAt,
      responseStream: {
        events: responseStreamEvents ?? []
      }
    });

    const titleToolCall = titleResponse.output.find(
      (outputItem): outputItem is ResponseFunctionToolCall =>
        isFunctionCallItem(outputItem) && outputItem.name === TASK_TITLE_TOOL_NAME
    );
    if (!titleToolCall) {
      return;
    }

    const parsedArguments = parseToolArguments(TASK_TITLE_TOOL_NAME, titleToolCall.arguments, taskTitleArgumentsSchema);
    if (!parsedArguments.ok) {
      return;
    }

    const normalizedTitle = normalizeTitleCandidate(parsedArguments.value.title);
    if (!normalizedTitle) {
      return;
    }

    const taggedTitle = applySourceTitlePrefix(normalizedTitle, input.source);
    if (!taggedTitle) {
      return;
    }

    await query(
      `UPDATE tasks
          SET title = $2,
              updated_at = now()
        WHERE id = $1
          AND (
            title IS NULL
            OR btrim(title) = ''
            OR title = 'New Task'
            OR lower(btrim(title)) = 'telegram task'
            OR lower(btrim(title)) = 'discord task'
            OR lower(btrim(title)) = 'github task'
            OR lower(btrim(title)) = 'email task'
          )`,
      [input.taskId, taggedTitle]
    );
  } catch (error) {
    const errorResponse = extractNetworkRequestErrorResponse(error);
    await emitNetworkRequestEvent(input.onNetworkRequest, {
      phase: "error",
      service: "openai_responses",
      endpoint: "responses.create.title",
      model: input.model ?? config.openai.defaultModel,
      baseUrl: input.provider.baseUrl,
      attempt: 1,
      error: error instanceof Error ? error.message : String(error),
      ...(errorResponse ? { errorResponse } : {}),
      responseStream: {
        events: readResponseStreamEvents(error)
      }
    });
    // Title generation is a best-effort enhancement and should never fail the run.
  }
}
