import { fileTypeFromBuffer } from "file-type";
import { labelMessageSender } from "../project-master/message-sender.js";
import fs from "node:fs";
import path from "node:path";
import type {
  ResponseInputContent,
  ResponseCustomToolCall,
  ResponseFunctionToolCall,
  ResponseInputItem,
  ResponseOutputItem
} from "openai/resources/responses/responses";
import type { PlatformModelCompatibilityMode, TaskRunToolOptions, TaskSource } from "@meowbert/shared";
import {
  buildTaskMessageMetadataLine,
  createTaskMessageMetadata,
  createDefaultEnvironmentJsonPayload,
  extractResponsesApiPayload,
  getSandboxNetworkEnabledOverride,
  normalizeTaskMessageMetadata,
  normalizeEnvironmentResponsesSettings,
  setSandboxNetworkEnabledOverride
} from "@meowbert/shared";
import { z } from "zod";
import type { TaskMessageRow, TaskMessageToolOptions } from "./types.js";
import { isApplyPatchCallItem } from "./apply-patch.js";
import { preparePdfView } from "../agent-tool-dispatch/pdf.js";
import { prepareToolOutputForModel } from "../agent-tool-dispatch/state.js";
import type { WorkspaceImageDetail } from "../workspaces/workspace-model-settings.js";
import {
  VIEW_PDF_DEFAULT_PAGE_START
} from "../agent-tools/index.js";
import {
  IMAGE_MIME_SNIFF_BYTES,
  VIEW_IMAGE_MAX_BYTES,
  VIEW_PDF_MAX_INPUT_BYTES,
  VIEW_PDF_MAX_OUTPUT_BYTES
} from "../agent-tool-dispatch/view-limits.js";

export function asText(content: Record<string, unknown>): string {
  if (typeof content.text === "string") {
    return content.text;
  }
  return JSON.stringify(content);
}

export function normalizeTitleCandidate(rawTitle: string): string | null {
  const trimmed = rawTitle.trim();
  if (!trimmed) {
    return null;
  }

  const compacted = trimmed.replace(/\s+/g, " ");
  const unwrapped = compacted.replace(/^["'`]+|["'`]+$/g, "").trim();
  const withoutTerminalPunctuation = unwrapped.replace(/[.!?]+$/g, "").trim();
  const normalized = (withoutTerminalPunctuation || unwrapped).slice(0, 240).trim();

  return normalized.length > 0 ? normalized : null;
}

function titlePrefixForSource(source: TaskSource): string {
  if (source === "telegram") {
    return "[Telegram] ";
  }
  if (source === "discord") {
    return "[Discord] ";
  }
  if (source === "github") {
    return "[GitHub] ";
  }
  if (source === "email") {
    return "[Email] ";
  }
  return "";
}

export function applySourceTitlePrefix(title: string, source: TaskSource): string {
  const prefix = titlePrefixForSource(source);
  if (!prefix) {
    return title;
  }

  if (title.startsWith(prefix)) {
    return title;
  }

  return `${prefix}${title}`.slice(0, 240).trim();
}

export function isAutoGeneratedTitlePlaceholder(title: string): boolean {
  const normalized = title.trim().toLowerCase();
  return (
    normalized === "" ||
    normalized === "new task" ||
    normalized === "telegram task" ||
    normalized === "discord task" ||
    normalized === "github task" ||
    normalized === "email task"
  );
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeToolIdList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return Array.from(new Set(
    value
      .filter((entry): entry is string => typeof entry === "string")
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0)
  ));
}

export function parseTaskMessageToolOptions(content: Record<string, unknown>): TaskMessageToolOptions {
  const rawTools = content.tools;
  if (!isPlainObject(rawTools)) {
    return {
      webSearch: false,
      memorySearch: false,
      scheduleTask: false,
      subtasks: false,
      computerUse: false,
      interactiveCanvas: false,
      enabledSkills: [],
      enabledSources: []
    };
  }

  return {
    webSearch: rawTools.webSearch === true,
    memorySearch: rawTools.memorySearch === true,
    scheduleTask: rawTools.scheduleTask === true,
    subtasks: rawTools.subtasks === true,
    computerUse: rawTools.computerUse === true,
    interactiveCanvas: rawTools.interactiveCanvas === true,
    enabledSkills: normalizeToolIdList(rawTools.enabledSkills),
    enabledSources: normalizeToolIdList(rawTools.enabledSources)
  };
}

export function parseTaskMessageAgentSelection(content: Record<string, unknown>): { id: string } | null {
  const rawAgent = content.agent;
  if (!isPlainObject(rawAgent) || typeof rawAgent.id !== "string") {
    return null;
  }

  const id = rawAgent.id.trim().toLowerCase();
  if (!id) {
    return null;
  }

  return { id };
}

export function pickRunToolOptions(messages: TaskMessageRow[]): TaskMessageToolOptions {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message.role !== "user") {
      continue;
    }

    return parseTaskMessageToolOptions(message.content_json);
  }

  return {
    webSearch: false,
    memorySearch: false,
      scheduleTask: false,
      subtasks: false,
      computerUse: false,
      interactiveCanvas: false,
      enabledSkills: [],
      enabledSources: []
  };
}

export function pickRunAgentSelection(messages: TaskMessageRow[]): { id: string } | null {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message.role !== "user") {
      continue;
    }

    return parseTaskMessageAgentSelection(message.content_json);
  }

  return null;
}

export function mergeTaskToolOptions(
  base: TaskMessageToolOptions,
  override?: TaskRunToolOptions | null
): TaskMessageToolOptions {
  if (!override) {
    return {
      webSearch: base.webSearch,
      memorySearch: base.memorySearch,
      scheduleTask: base.scheduleTask,
      subtasks: base.subtasks,
      computerUse: base.computerUse,
      interactiveCanvas: base.interactiveCanvas,
      enabledSkills: normalizeToolIdList(base.enabledSkills),
      enabledSources: normalizeToolIdList(base.enabledSources)
    };
  }

  const enabledSkills = Array.isArray(override.enabledSkills)
    ? normalizeToolIdList(override.enabledSkills)
    : normalizeToolIdList(base.enabledSkills);
  const enabledSources = Array.isArray(override.enabledSources)
    ? normalizeToolIdList(override.enabledSources)
    : normalizeToolIdList(base.enabledSources);

  return {
    webSearch: typeof override.webSearch === "boolean" ? override.webSearch : base.webSearch,
    memorySearch: typeof override.memorySearch === "boolean" ? override.memorySearch : base.memorySearch,
    scheduleTask: typeof override.scheduleTask === "boolean" ? override.scheduleTask : base.scheduleTask,
    subtasks: typeof override.subtasks === "boolean" ? override.subtasks : base.subtasks,
    computerUse: typeof override.computerUse === "boolean" ? override.computerUse : base.computerUse,
    interactiveCanvas: typeof override.interactiveCanvas === "boolean" ? override.interactiveCanvas : base.interactiveCanvas,
    enabledSkills,
    enabledSources
  };
}

function deepCloneJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => deepCloneJsonValue(entry));
  }

  if (isPlainObject(value)) {
    const cloned: Record<string, unknown> = {};
    for (const [key, entry] of Object.entries(value)) {
      cloned[key] = deepCloneJsonValue(entry);
    }
    return cloned;
  }

  return value;
}

export function deepMergeJsonObjects(
  base: Record<string, unknown>,
  override: Record<string, unknown>
): Record<string, unknown> {
  const merged: Record<string, unknown> = {};
  const keys = new Set([...Object.keys(base), ...Object.keys(override)]);

  for (const key of keys) {
    const hasOverride = Object.prototype.hasOwnProperty.call(override, key);
    if (!hasOverride) {
      merged[key] = deepCloneJsonValue(base[key]);
      continue;
    }

    const overrideValue = override[key];
    const baseValue = base[key];
    if (isPlainObject(baseValue) && isPlainObject(overrideValue)) {
      merged[key] = deepMergeJsonObjects(baseValue, overrideValue);
      continue;
    }

    merged[key] = deepCloneJsonValue(overrideValue);
  }

  return merged;
}

function isFinalResponseFunctionCallItem(item: ResponseInputItem): item is ResponseInputItem & {
  type: "function_call";
  call_id: string;
  name: "final_response";
} {
  return typeof item === "object"
    && item !== null
    && "type" in item
    && item.type === "function_call"
    && "name" in item
    && item.name === "final_response"
    && "call_id" in item
    && typeof item.call_id === "string";
}

function isFunctionCallOutputForCallId(item: ResponseInputItem, callIds: Set<string>): boolean {
  return typeof item === "object"
    && item !== null
    && "type" in item
    && item.type === "function_call_output"
    && "call_id" in item
    && typeof item.call_id === "string"
    && callIds.has(item.call_id);
}

function hasAssistantInputItem(items: ResponseInputItem[]): boolean {
  return items.some((item) => (
    typeof item === "object"
    && item !== null
    && "role" in item
    && item.role === "assistant"
    && "content" in item
  ));
}

function asPersistedResponseInputItem(rawItem: unknown): ResponseInputItem | null {
  if (!rawItem || typeof rawItem !== "object") {
    return null;
  }

  const candidate = rawItem as { type?: unknown; role?: unknown; content?: unknown };
  if (typeof candidate.type === "string") {
    return rawItem as ResponseInputItem;
  }

  if (typeof candidate.role === "string" && candidate.content !== undefined) {
    return rawItem as ResponseInputItem;
  }

  return null;
}

function parsePersistedResponseItems(message: TaskMessageRow): ResponseInputItem[] {
  const content = message.content_json;
  const rawItems = content.response_items;
  if (!Array.isArray(rawItems)) {
    return [];
  }

  const items: ResponseInputItem[] = [];
  const finalResponseCallIds = new Set<string>();

  for (const rawItem of rawItems) {
    const item = asPersistedResponseInputItem(rawItem);
    if (!item) {
      continue;
    }

    if (isFinalResponseFunctionCallItem(item)) {
      finalResponseCallIds.add(item.call_id);
      continue;
    }

    items.push(item);
  }

  if (finalResponseCallIds.size === 0) {
    return items;
  }

  const filteredItems = items.filter((item) => !isFunctionCallOutputForCallId(item, finalResponseCallIds));
  const visibleText = typeof content.text === "string" ? content.text.trim() : "";
  if (
    message.role === "assistant"
    && visibleText.length > 0
    && !hasAssistantInputItem(filteredItems)
  ) {
    filteredItems.push(buildAssistantHistoryItem(visibleText));
  }

  return filteredItems;
}

function resolveMessageText(text: string, taskInputDir: string): string {
  // Normalize both legacy ../inputs/ references and current inputs/ references to the
  // absolute task inputs directory path so the model sees a single unambiguous location.
  return text.replace(
    /(^|[\s([{"'])(?:\.\.\/|\.\/)?inputs\//g,
    (_match, prefix: string) => `${prefix}${taskInputDir}/`
  );
}

interface TaskMessageAttachment {
  kind: "note" | "file" | "directory";
  label: string;
  content: string;
  relativePath?: string;
  sizeBytes?: number | null;
  forceInclude?: boolean;
}

function parseTaskMessageAttachments(content: Record<string, unknown>): TaskMessageAttachment[] {
  if (!Array.isArray(content.attachments)) {
    return [];
  }

  return content.attachments.reduce<TaskMessageAttachment[]>((attachments, rawAttachment) => {
    if (!rawAttachment || typeof rawAttachment !== "object") {
      return attachments;
    }

    const candidate = rawAttachment as {
      kind?: unknown;
      label?: unknown;
      content?: unknown;
      relativePath?: unknown;
      sizeBytes?: unknown;
      forceInclude?: unknown;
    };
    if (
      (candidate.kind !== "note" && candidate.kind !== "file" && candidate.kind !== "directory")
      || typeof candidate.label !== "string"
      || typeof candidate.content !== "string"
    ) {
      return attachments;
    }

    attachments.push({
      kind: candidate.kind,
      label: candidate.label,
      content: candidate.content,
      ...(typeof candidate.relativePath === "string" ? { relativePath: candidate.relativePath } : {}),
      ...(typeof candidate.sizeBytes === "number" && Number.isFinite(candidate.sizeBytes)
        ? { sizeBytes: candidate.sizeBytes }
        : candidate.sizeBytes === null
          ? { sizeBytes: null }
          : {}),
      ...(candidate.forceInclude === true ? { forceInclude: true } : {})
    });
    return attachments;
  }, []);
}

function resolveAttachmentAbsolutePath(attachment: TaskMessageAttachment, taskInputDir: string): string | null {
  const attachmentPath = attachment.relativePath ?? attachment.content;
  if (attachment.kind !== "file" || typeof attachmentPath !== "string" || attachmentPath.trim().length === 0) {
    return null;
  }

  const normalizedPath = attachmentPath.replace(/\\/g, "/").replace(/^\.?\//, "");
  if (normalizedPath === "inputs" || normalizedPath.startsWith("inputs/")) {
    return path.resolve(taskInputDir, normalizedPath === "inputs" ? "." : normalizedPath.slice("inputs/".length));
  }

  if (path.isAbsolute(attachmentPath)) {
    return path.resolve(attachmentPath);
  }

  return path.resolve(taskInputDir, attachmentPath);
}

function isLikelyTextAttachment(attachment: TaskMessageAttachment, filePath: string): boolean {
  const lowerName = `${attachment.label} ${filePath}`.toLowerCase();
  return /\.(txt|md|markdown|csv|tsv|json|jsonl|yaml|yml|xml|html|htm|css|js|jsx|ts|tsx|py|rb|go|rs|java|c|cc|cpp|h|hpp|sh|zsh|bash|sql|toml|ini|env|log)$/i.test(lowerName);
}

function buildForceIncludeFailureItem(attachment: TaskMessageAttachment, reason: string): ResponseInputItem {
  return {
    role: "user",
    content: `[Attachment force include skipped: ${attachment.label}. ${reason}]`
  };
}

function buildForceIncludeMetadataItem(attachment: TaskMessageAttachment): ResponseInputItem {
  return {
    role: "user",
    content: [
      `[Attachment marked force include: ${attachment.label}]`,
      `Kind: ${attachment.kind}`,
      `Path/content: ${attachment.relativePath ?? attachment.content}`,
      typeof attachment.sizeBytes === "number" ? `Size: ${attachment.sizeBytes} bytes` : null
    ].filter((line): line is string => typeof line === "string").join("\n")
  };
}

async function tryBuildForceIncludedAttachmentItems(
  attachment: TaskMessageAttachment,
  taskInputDir: string,
  imageDetail: WorkspaceImageDetail,
  mode: "normal" | "quick"
): Promise<ResponseInputItem[]> {
  if (mode === "normal" && attachment.forceInclude !== true) {
    return [];
  }

  if (mode === "quick" && attachment.kind !== "file") {
    return [];
  }

  if (attachment.kind === "note") {
    return [{
      role: "user",
      content: `Force-included note attachment (${attachment.label}):\n${attachment.content}`
    }];
  }

  const filePath = resolveAttachmentAbsolutePath(attachment, taskInputDir);
  if (!filePath) {
    if (mode === "quick") {
      return [];
    }
    return [buildForceIncludeMetadataItem(attachment)];
  }

  try {
    const fileStats = fs.statSync(filePath);
    if (!fileStats.isFile()) {
      return [buildForceIncludeMetadataItem(attachment)];
    }

    const lowerPath = filePath.toLowerCase();
    if (lowerPath.endsWith(".pdf")) {
      if (mode === "quick") {
        return [];
      }
      if (fileStats.size > VIEW_PDF_MAX_INPUT_BYTES) {
        return [buildForceIncludeFailureItem(attachment, "PDF exceeds viewer limit.")];
      }
      const preparedPdf = await preparePdfView({
        fileBuffer: fs.readFileSync(filePath),
        fileName: path.basename(filePath),
        pageStart: VIEW_PDF_DEFAULT_PAGE_START,
        pageEnd: Number.MAX_SAFE_INTEGER,
        maxOutputBytes: VIEW_PDF_MAX_OUTPUT_BYTES
      });
      const fileContent: ResponseInputContent = {
        type: "input_file",
        file_data: `data:application/pdf;base64,${preparedPdf.outputBuffer.toString("base64")}`,
        filename: preparedPdf.outputFileName
      };
      return [{ role: "user", content: [fileContent] }];
    }

    const header = fs.readFileSync(filePath).subarray(0, IMAGE_MIME_SNIFF_BYTES);
    const imageMimeType = await detectImageMimeTypeFromBuffer(header);
    if (imageMimeType) {
      if (fileStats.size > VIEW_IMAGE_MAX_BYTES) {
        return [buildForceIncludeFailureItem(attachment, "Image exceeds viewer limit.")];
      }
      const imageContent = {
        type: "input_image",
        detail: imageDetail,
        image_url: `data:${imageMimeType};base64,${fs.readFileSync(filePath).toString("base64")}`
      } as ResponseInputContent;
      return [{
        role: "user",
        content: [
          {
            type: "input_text",
            text: `Force-included image file: ${attachment.label}`
          } as ResponseInputContent,
          imageContent
        ]
      }];
    }

    if (mode === "quick") {
      return [];
    }

    if (isLikelyTextAttachment(attachment, filePath)) {
      return [{
        role: "user",
        content: `Force-included file (${attachment.label}, ${attachment.relativePath ?? attachment.content}):\n${fs.readFileSync(filePath, "utf8")}`
      }];
    }

    return [buildForceIncludeMetadataItem(attachment)];
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return [buildForceIncludeFailureItem(attachment, message)];
  }
}

function resolveMessageReplayMetadata(message: TaskMessageRow): unknown {
  if (message.role === "tool") {
    return null;
  }

  return normalizeTaskMessageMetadata(message.message_metadata_json)
    ?? createTaskMessageMetadata(message.created_at);
}

function buildReplayMetadataSystemItem(message: TaskMessageRow): ResponseInputItem | null {
  const metadataLine = buildTaskMessageMetadataLine(resolveMessageReplayMetadata(message));
  if (!metadataLine) {
    return null;
  }

  return {
    role: "system",
    content: metadataLine
  };
}

function isMetadataEligiblePersistedItem(item: ResponseInputItem): boolean {
  if (typeof item !== "object" || item === null || !("role" in item) || !("content" in item)) {
    return false;
  }

  if (item.role !== "user" && item.role !== "assistant" && item.role !== "system") {
    return false;
  }

  return typeof item.content === "string";
}

export function stripProviderManagedItemId(item: ResponseInputItem): ResponseInputItem {
  if (typeof item !== "object" || item === null || !("id" in item)) {
    return item;
  }

  if ("type" in item && item.type === "compaction") {
    return item;
  }

  const { id: _ignoredId, ...rest } = item as ResponseInputItem & { id?: string };
  return rest as ResponseInputItem;
}

type ResponseToolCallKind = "function_call" | "custom_tool_call" | "apply_patch_call";

function getResponseToolCallKind(item: ResponseInputItem): ResponseToolCallKind | null {
  if (typeof item !== "object" || item === null || !("type" in item) || !("call_id" in item)) {
    return null;
  }

  const record = item as unknown as { type?: unknown; call_id?: unknown };
  if (typeof record.call_id !== "string") {
    return null;
  }

  return record.type === "function_call" || record.type === "custom_tool_call" || record.type === "apply_patch_call"
    ? record.type
    : null;
}

function getResponseToolOutputType(kind: ResponseToolCallKind): string {
  return kind === "function_call"
    ? "function_call_output"
    : kind === "custom_tool_call"
      ? "custom_tool_call_output"
      : "apply_patch_call_output";
}

function isResponseToolOutput(item: ResponseInputItem): boolean {
  if (typeof item !== "object" || item === null || !("type" in item)) {
    return false;
  }

  const type = (item as unknown as { type?: unknown }).type;
  return type === "function_call_output" || type === "custom_tool_call_output" || type === "apply_patch_call_output";
}

function getCallId(item: ResponseInputItem): string | null {
  const callId = (item as { call_id?: unknown }).call_id;
  return typeof callId === "string" ? callId : null;
}

function isSyntheticRecoveredOutput(item: ResponseInputItem): boolean {
  if (typeof item !== "object" || item === null || !("output" in item)) {
    return false;
  }

  const output = (item as unknown as { output?: unknown }).output;
  return typeof output === "string" && output.includes("Recovered missing");
}

function buildRecoveredToolOutput(kind: ResponseToolCallKind, callId: string): ResponseInputItem {
  if (kind === "function_call") {
    return {
      type: "function_call_output",
      call_id: callId,
      output: JSON.stringify({ error: "Recovered missing function_call_output from historical task state." })
    };
  }

  if (kind === "custom_tool_call") {
    return {
      type: "custom_tool_call_output",
      call_id: callId,
      output: "Recovered missing custom_tool_call_output from historical task state."
    } as unknown as ResponseInputItem;
  }

  return {
    type: "apply_patch_call_output",
    call_id: callId,
    status: "failed",
    output: "Recovered missing apply_patch_call_output from historical task state."
  } as unknown as ResponseInputItem;
}

function parseToolMessageResponseItems(content: Record<string, unknown>): ResponseInputItem[] {
  const entries: Array<[string, string]> = [
    ["response_function_call", "function_call"],
    ["response_function_output", "function_call_output"],
    ["response_custom_tool_call", "custom_tool_call"],
    ["response_custom_tool_output", "custom_tool_call_output"],
    ["response_apply_patch_call", "apply_patch_call"],
    ["response_apply_patch_output", "apply_patch_call_output"]
  ];

  return entries.flatMap(([key, type]) => {
    const raw = content[key];
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
      return [];
    }
    return [{ ...(raw as Record<string, unknown>), type } as ResponseInputItem];
  });
}

/**
 * Give every tool call in `items` exactly one output, keeping everything already present in its
 * original order. Replayed history must match what the provider saw, or its prompt cache misses
 * from that point on. A call with no output gets the real one from `fallbackItems` when it exists,
 * otherwise a placeholder, placed after the call's batch. Duplicate calls, duplicate outputs and
 * outputs without a call are dropped, since providers reject them.
 */
export function reconstructResponseInputItems(
  items: ResponseInputItem[],
  options: { omitReasoning?: boolean; fallbackItems?: ResponseInputItem[] } = {}
): ResponseInputItem[] {
  const normalizedItems = items
    .filter((item) => !options.omitReasoning || item.type !== "reasoning")
    .map((item) => stripProviderManagedItemId(item));
  const indexOutputs = (source: ResponseInputItem[]): Map<string, Array<{ index: number; item: ResponseInputItem }>> => {
    const outputs = new Map<string, Array<{ index: number; item: ResponseInputItem }>>();
    source.forEach((item, index) => {
      const callId = isResponseToolOutput(item) ? getCallId(item) : null;
      if (!callId) return;
      const entries = outputs.get(callId) ?? [];
      entries.push({ index, item });
      outputs.set(callId, entries);
    });
    return outputs;
  };
  const outputsByCall = indexOutputs(normalizedItems);
  const fallbackOutputsByCall = indexOutputs(options.fallbackItems ?? []);
  const outputsOfKind = (
    outputs: Map<string, Array<{ index: number; item: ResponseInputItem }>>,
    callId: string,
    kind: ResponseToolCallKind,
    after = -1
  ): ResponseInputItem[] => (outputs.get(callId) ?? [])
    .filter((entry) => entry.index > after && (entry.item as { type?: unknown }).type === getResponseToolOutputType(kind))
    .map((entry) => entry.item);
  const preferRealOutput = (candidates: ResponseInputItem[]): ResponseInputItem | undefined =>
    candidates.find((candidate) => !isSyntheticRecoveredOutput(candidate)) ?? candidates[0];

  const result: ResponseInputItem[] = [];
  const emittedCalls = new Map<string, ResponseToolCallKind>();
  const answeredCalls = new Set<string>();
  let owedOutputs: ResponseInputItem[] = [];

  normalizedItems.forEach((item, index) => {
    const kind = getResponseToolCallKind(item);
    const callId = getCallId(item);
    if (kind && callId) {
      if (emittedCalls.has(callId)) return;
      emittedCalls.set(callId, kind);
      result.push(item);
      if (outputsOfKind(outputsByCall, callId, kind, index).length === 0) {
        const fallback = preferRealOutput(outputsOfKind(fallbackOutputsByCall, callId, kind));
        owedOutputs.push(fallback ? stripProviderManagedItemId(fallback) : buildRecoveredToolOutput(kind, callId));
        answeredCalls.add(callId);
      }
      return;
    }

    if (isResponseToolOutput(item)) {
      const callKind = callId ? emittedCalls.get(callId) : undefined;
      if (!callId || !callKind || answeredCalls.has(callId)) return;
      const output = preferRealOutput(outputsOfKind(outputsByCall, callId, callKind));
      if (!output) return;
      answeredCalls.add(callId);
      result.push(output);
      return;
    }

    result.push(...owedOutputs, item);
    owedOutputs = [];
  });

  result.push(...owedOutputs);
  return result;
}

// A tool called from inside exec is shown in the task but was never a model call; exec's own output
// already carries what the model saw.
function isCodeModeNestedToolMessage(message: TaskMessageRow): boolean {
  return message.role === "tool" && typeof message.content_json.code_mode_parent_call_id === "string";
}

export function collectTaskToolOutputItems(messages: TaskMessageRow[]): ResponseInputItem[] {
  const outputs: ResponseInputItem[] = [];
  for (const message of messages) {
    if (isCodeModeNestedToolMessage(message)) continue;
    const candidates = [
      ...parsePersistedResponseItems(message),
      ...(message.role === "tool" ? parseToolMessageResponseItems(message.content_json) : [])
    ];
    for (const item of candidates) {
      if (isResponseToolOutput(item)) outputs.push(item);
    }
  }
  return outputs;
}

function collectPersistedToolCallIds(messages: TaskMessageRow[]): Set<string> {
  const callIds = new Set<string>();
  for (const message of messages) {
    for (const item of parsePersistedResponseItems(message)) {
      const callId = getResponseToolCallKind(item) ? getCallId(item) : null;
      if (callId) callIds.add(callId);
    }
  }
  return callIds;
}

/**
 * Rebuild the model input for a new run from task history.
 *
 * Persisted run items are exactly what the model saw, so they are replayed verbatim. Tool
 * messages are display records that also carry the tool's call and output: they stand in for a
 * call that no run persisted (an interrupted run), and otherwise only supply that call's output
 * if the run lost it. Replaying them alongside the run's own items would send a second, different
 * copy of each output.
 */
export async function mapMessagesForResponsesInput(
  messages: TaskMessageRow[],
  taskInputDir: string,
  imageDetail: WorkspaceImageDetail,
  options: { quickMode?: boolean; sendMetadataToModel?: boolean } = {}
): Promise<ResponseInputItem[]> {
  const output: ResponseInputItem[] = [];
  const fallbackOutputs: ResponseInputItem[] = [];
  const persistedCallIds = collectPersistedToolCallIds(messages);

  for (const message of messages) {
    const persistedItems = parsePersistedResponseItems(message);
    if (persistedItems.length > 0) {
      for (const persistedItem of persistedItems) {
        const item = stripProviderManagedItemId(persistedItem);
        output.push(item);
        if (options.sendMetadataToModel === true && isMetadataEligiblePersistedItem(item)) {
          const metadataItem = buildReplayMetadataSystemItem(message);
          if (metadataItem) output.push(metadataItem);
        }
      }
      continue;
    }

    if (isCodeModeNestedToolMessage(message)) {
      continue;
    }

    if (message.role === "tool") {
      const responseItems = parseToolMessageResponseItems(message.content_json);
      if (responseItems.length > 0) {
        const persisted = responseItems.some((item) => {
          const callId = getCallId(item);
          return callId !== null && persistedCallIds.has(callId);
        });
        if (persisted) {
          fallbackOutputs.push(...responseItems.filter(isResponseToolOutput));
        } else {
          output.push(...responseItems);
        }
        continue;
      }

      const legacyToolPayload = typeof message.content_json.tool === "string"
        ? prepareToolOutputForModel(message.content_json.tool, message.content_json)
        : message.content_json;
      output.push({
        role: "user",
        content: `Shell tool result: ${JSON.stringify(legacyToolPayload)}`
      });
      continue;
    }

    output.push({
      role: message.role,
      content: labelMessageSender(message.content_json, resolveMessageText(asText(message.content_json), taskInputDir))
    });
    if (options.sendMetadataToModel === true) {
      const metadataItem = buildReplayMetadataSystemItem(message);
      if (metadataItem) output.push(metadataItem);
    }

    for (const attachment of parseTaskMessageAttachments(message.content_json)) {
      output.push(...await tryBuildForceIncludedAttachmentItems(
        attachment,
        taskInputDir,
        imageDetail,
        options.quickMode === true ? "quick" : "normal"
      ));
    }
  }

  return reconstructResponseInputItems(output, { fallbackItems: fallbackOutputs });
}

export function parseToolArguments<T>(
  toolName: string,
  rawArguments: string,
  schema: z.ZodSchema<T>
): { ok: true; value: T } | { ok: false; error: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawArguments);
  } catch {
    return {
      ok: false,
      error: `${toolName} arguments are not valid JSON`
    };
  }

  const validated = schema.safeParse(parsed);
  if (!validated.success) {
    const details = validated.error.issues.map((issue) => issue.message).join("; ");
    return {
      ok: false,
      error: `${toolName} arguments are invalid: ${details}`
    };
  }

  return {
    ok: true,
    value: validated.data
  };
}

export function toContinuityInputItem(item: ResponseOutputItem, compatibilityModes?: PlatformModelCompatibilityMode[]): ResponseInputItem | null {
  if (item.type === "reasoning") {
    const hasEncryptedContent = typeof item.encrypted_content === "string" && item.encrypted_content.length > 0;

    if (!hasEncryptedContent && compatibilityModes?.includes("forcePersistReasoningContent")) {
      // Synthesize encrypted_content from summary text so reasoning persists across turns
      const summaryText = item.summary
        ?.filter((s): s is { type: "summary_text"; text: string } => s.type === "summary_text")
        .map((s) => s.text)
        .join("\n");

      if (summaryText && summaryText.length > 0) {
        return {
          type: "reasoning",
          summary: item.summary,
          encrypted_content: `<think>${summaryText}</think>`
        } as unknown as ResponseInputItem;
      }
    }

    const reasoningItem = {
      type: "reasoning",
      summary: item.summary,
      encrypted_content: item.encrypted_content ?? null
    } as unknown as ResponseInputItem;
    return reasoningItem;
  }

  if (item.type === "message" || item.type === "function_call" || item.type === "custom_tool_call" || item.type === "web_search_call") {
    return stripProviderManagedItemId(item);
  }

  if (isApplyPatchCallItem(item)) {
    return stripProviderManagedItemId(item as unknown as ResponseInputItem);
  }

  return null;
}

export function isFunctionCallItem(item: ResponseOutputItem): item is ResponseFunctionToolCall {
  return item.type === "function_call";
}

export function isCustomToolCallItem(item: ResponseOutputItem): item is ResponseCustomToolCall {
  return item.type === "custom_tool_call";
}

export function buildAssistantHistoryItem(text: string): ResponseInputItem {
  return {
    role: "assistant",
    content: text
  };
}

const SUPPORTED_VIEW_IMAGE_MIME_TYPES = new Set([
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/webp",
  "image/bmp"
]);

export async function detectImageMimeTypeFromBuffer(buffer: Buffer): Promise<string | null> {
  const detected = await fileTypeFromBuffer(buffer);
  if (!detected) {
    return null;
  }

  return SUPPORTED_VIEW_IMAGE_MIME_TYPES.has(detected.mime) ? detected.mime : null;
}

export function normalizeEnvironmentJsonPayload(rawPayload: unknown): Record<string, unknown> {
  const payload = isPlainObject(rawPayload)
    ? { ...rawPayload }
    : createDefaultEnvironmentJsonPayload();

  // Strip legacy field before response-payload normalization so it never leaks into `responses`.
  delete payload.max_context_window_tokens;

  const normalized = normalizeEnvironmentResponsesSettings(payload);
  return setSandboxNetworkEnabledOverride(normalized, getSandboxNetworkEnabledOverride(normalized));
}

export function extractModelRequestPayload(payload: Record<string, unknown>): Record<string, unknown> {
  return extractResponsesApiPayload(payload);
}

export function isNetworkRequestLoggingEnabled(payload: Record<string, unknown>): boolean {
  const debugConfig = payload.debug;
  if (!isPlainObject(debugConfig)) {
    return false;
  }

  return debugConfig.log_network_requests === true || debugConfig.logNetworkRequests === true;
}
